language: java
jdk:
- oraclejdk7

install: true

script:
- "./gradlew reobf"

branches:
  only:
  - master

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/fileHashes/
- rm -rf $HOME/.gradle/caches/minecraft/deobfedDeps/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag -m "Development Build ${TRAVIS_BUILD_NUMBER}" "dev-build-${TRAVIS_BUILD_NUMBER}"
- git push -q ${GITHUB_REPO} --tags
deploy:
  provider: releases
  skip_cleanup: true
  file: build/libs/*.jar
  file_glob: true
  prerelease: true
  on:
    tags: false # always deploy, tag gets created in before_deploy
  api_key:
    secure: SgWjb9Y450fYotowUlCAqXeXG8EUmG4yUNhhEe5cNO5kcQhG4qdxSg15rb4y7tAnyKulcaqd7D2YPpYkvJUH5hiRHubvsI/1br/BXNWOf1Q1y5z+Ycd2VJp/TEj8GjLZRn5ZHHCRaB3AwqbYxeyh6gCwZbQdcZcXWALr0jpHb2sP3QmFplMt2+FYgZfhxvmL/63kvmtdc3rocKmd4iH+R0KQVBl5OHyhHKDW9Cjm423fcRpHPi0FYa+Mr5M3HO3bUbbLVoZzdGNf4pJ9oINJXpWJiUfQAoo4vQ/OyQM6+2v0FppjsES/3pKHwcyTqQV1ZYMT+xNeLM9QmSIg5I/7FvjQl885tMiyweTF+OAtheg3UYbsR6MymsfCMFTY9BzQfkYGPB4SXnG4Iy32S2eFQDZNDXzr6BneelaAkr9sJxlR+NnTQCiftcAcH4XfJf4LLsXfuWDsBmFlHhpOBoU0kEzlJwz3o6LIqJlWrfmfdsneqDhlRXO5H+kgaUaFjgmDEgTXlG1WTlW6yt/SZ3YEwJfmRisSxAJICywgFE1mt3Qk4ox8enUjR5iQtZkkoHvqWnVwJezzZAwb9NJVEIh7uYDSNli8A2Og/Y48RnrVNUv+x4TYhTDb+yWX36kfp4cq7WGtRwDuJLprOhIdhsFVq5n7uWQMsBo5BGBRWE1xwyI=
